feat: Skeleton UI framework, creating functional pages
szattila98/veryrezsi pull request #72
Opened 2023-05-07 17:56 UTC by djavorek

2023-06-09 06:47 UTC, szattila98 commented
I wanted to view your work so I started up everything in docker and I saw this when I wanted to login.
![image](https://github.com/szattila98/veryrezsi/assets/37137309/b222cf92-637d-43cf-b309-71b9adc39b8c)
Locally it works fine, I will be opening an issue to resolve this.

The design looks so cool! 🤩

2023-06-09 08:03 UTC, szattila98 requested changes
Very nice work, I had a few comments. I didn't know that you are a designer prodigy. 😁

2023-06-16 05:40 UTC, djavorek commented on client/src/app.css
> -@tailwind utilities;
Nope, see: https://www.skeleton.dev/docs/get-started
They are highlighted close to the top of the page, to be removed.

2023-06-16 05:42 UTC, djavorek commented on client/src/lib/components/common/AlertMsg.svelte
> +	<div class="alert-message">
Unfortunately yes,
See: https://www.skeleton.dev/elements/alerts

2023-06-16 05:48 UTC, djavorek commented on client/src/lib/components/common/ThemedValidationHint.svelte
I would prefer not to. It might be possible, but I cannot see a good solution, they are quite different.

I think we are good for now until we have 2 common components :D

2023-06-16 05:52 UTC, djavorek commented on client/src/lib/components/common/ThemedValidationHint.svelte
> +	export let hintProps: object = {};
Good idea. I tried it, but `HintProps` is only exported to module level, but not exported from _svelte-use-forms_ :(

2023-06-16 05:56 UTC, djavorek commented on client/src/lib/components/common/ThemedValidationHint.svelte
> +	export let hintProps: object = {};
We can also copy their prop def and roll with it, but we will need to follow their later modifications then.
What do you think?

2023-06-16 05:58 UTC, djavorek commented
> I wanted to view your work so I started up everything in docker and I saw this when I wanted to login. ![image](https://user-images.githubusercontent.com/37137309/244613664-b222cf92-637d-43cf-b309-71b9adc39b8c.png) Locally it works fine, I will be opening an issue to resolve this.
> 
> The design looks so cool! 🤩

I am sad to see this error, but I will pick up that issue next. I'm glad you like this look 😎

2023-06-16 05:59 UTC, djavorek commented on client/src/routes/+page.svelte
> +
Sure, it was unused. Deleted for now.

2023-06-16 05:59 UTC, djavorek commented on client/src/routes/start-tracking/+page.svelte
> +
Deleted it for now.

2023-06-16 15:11 UTC, szattila98 commented on client/src/lib/components/common/ThemedValidationHint.svelte
> +	export let hintProps: object = {};
Could you write a github issue to the author about exporting it? He seemed like a cool dude, ready to take action.

2023-06-17 16:22 UTC, szattila98 approved these changes

2023-06-18 17:45 UTC, merged